# Generated by Django 5.0 on 2023-12-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='subject',
            field=models.CharField(default='Default Subject', max_length=200),
        ),
    ]
