# Generated by Django 5.0 on 2023-12-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_content_board_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='category',
        ),
        migrations.RemoveField(
            model_name='board',
            name='title',
        ),
    ]
